### PR TITLE
Instructor Search

### LINKED ISSUE #136: [Bug] Filters on instructor page have no effect
### Expected Behavior

image

On this page, the filters should change the number and type of semesters shown

### Steps to Reproduce

Attempt to change the filters. No effect

### Device Information

Desktop/Mobile: Desktop
OS: macOS Sonoma
Browser Version: Safari 17.0

### PR DESCRIPTION
**Pull request by Xavilien**
# Description

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

To test, set serializableCheck in store.ts:81 to false so that you don't get this error:
image

- [x] Search various professors
- [x] Scroll to different pages, then change the search query
- [x] Play around with the filters 

**Test Configuration**:

- Node.js version: 18.18.0
- Desktop/Mobile: Desktop
- OS: Mac Sonoma
- Browser: Safari

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: frontend/src/app/cache.ts [hunk 1]
```diff
@@ -78,6 +85,11 @@ export const selectFCEResultsForInstructor =
     (state: RootState): FCE[] | undefined =>
       state.cache.instructorResults[name];
 
+export const selectProfessors = (search: string) => (state: RootState) =>
+  state.cache.allProfessors.filter((prof) =>
+    prof.name.toLowerCase().includes(search.toLowerCase())
```
Comment (Lhwhatever) [inline frontend/src/app/cache.ts:90]: i wonder if we can improve this logic.
for example, searching professors by (firstname lastname) instead of (lastname, firstname)

Comment (Lhwhatever) [reply frontend/src/app/cache.ts:90]: could also be a feature for a later PR

File: frontend/src/components/SideNav.tsx [hunk 2]
```diff
@@ -80,6 +81,12 @@ export const SideNav = ({ activePage }) => {
         newTab
         active={false}
       />
+      <SideNavItem
+        icon={UserCircleIcon}
+        text="Professors"
```
Comment (Lhwhatever) [inline frontend/src/components/SideNav.tsx:86]: we should probably change the term "Professors" to "Instructors"
not all course instructors are necessarily professors

**Review by Lhwhatever — CHANGES_REQUESTED** [review]
see comment about Professors/Instructors

**Comment by Xavilien** [comment]
@Lhwhatever have made the refactoring from "professor" to "instructors". Have also used fuse.js for fuzzy searching. It's not perfect but it may be slightly better than the previous version. Also refactored some code so that searching is speedier so now it should be just as fast (if not faster) than the course search. Do let me know if there are any other comments!

File: frontend/src/app/cache.ts [hunk 3]
```diff
@@ -45,6 +52,11 @@ const initialState: CacheState = {
   coursesLoading: false,
   exactResultsCourses: [],
   allCourses: [],
+  allInstructors: [],
+  fuseIndex: null,
```
Comment (Lhwhatever) [inline frontend/src/app/cache.ts:56]: the type for `fuseIndex` seems not to be nullable here?

File: frontend/src/app/cache.ts [hunk 4]
```diff
@@ -187,6 +215,19 @@ export const cacheSlice = createSlice({
...
+
+    builder
+      .addCase(fetchAllInstructors.pending, (state) => {
+        state.instructorsLoading = true;
+      })
+      .addCase(fetchAllInstructors.fulfilled, (state, action) => {
+        state.instructorsLoading = false;
+        if (action.payload) {
+          state.allInstructors = action.payload;
+          state.fuseIndex = Fuse.createIndex(["instructor"], action.payload).toJSON();
```
Comment (Lhwhatever) [inline frontend/src/app/cache.ts:227]: I'm not too sure on the `Fuse` library API so I will trust this here

**Review by Lhwhatever — CHANGES_REQUESTED** [review]

File: frontend/src/app/cache.ts (hunk 4 above)
Comment (Xavilien) [reply frontend/src/app/cache.ts:227]: Was basing it of this https://www.fusejs.io/api/indexing.html#fuse-createindex

**Review by Lhwhatever — APPROVED** [review]
